<?php
/**
 * 任务
 *
 * @package models.task_model
 * @since 1.0
 */
class Signin_model extends MY_Model
{
    /**
     * @var string $tableName 表名
     */
    public $tableName = 'signin';
    public $primaryKey = 'id';

    /**
     * 构造方法
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Find Record By Attributes
     *
     * @param array $where
     * @return array
     */
    public function findByAttributes($where = array(), $order = '')
    {
        return parent::findByAttributes($where, $order);
    }

    public function findAll($where = array(), $limit = 0, $offset = 0, $sort = NULL)
    {
        return parent::findAll($where, $limit, $offset, $sort); // TODO: Change the autogenerated stub
    }

    public function insertData($data = array())
    {
        return parent::insertData($data);
    }

    public function findByPk($pk, $where = array())
    {
        return parent::findByPk($pk, $where); // TODO: Change the autogenerated stub
    }

    public function updateByPk($pk, $attributes, $where = array())
    {
        return parent::updateByPk($pk, $attributes, $where); // TODO: Change the autogenerated stub
    }

    public function updateAll($attributes, $where = array())
    {
        return parent::updateAll($attributes, $where); // TODO: Change the autogenerated stub
    }

    public function count($where = array())
    {
        return parent::count($where); // TODO: Change the autogenerated stub
    }
}

